# Generated by Django 5.0.6 on 2024-06-13 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('sku_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('photo_image', models.ImageField(upload_to='dashboard/media')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
