# Generated by Django 5.0.6 on 2024-06-13 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_image',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/media'),
        ),
        migrations.AddField(
            model_name='product',
            name='localization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.localization'),
        ),
    ]
